[build]
  base = "client"
  publish = "build"
  command = "CI=false npm run build"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://your-backend-url.railway.app/api"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://your-backend-url.railway.app/api"
