# Render.yaml - Render deployment configuration
services:
  - type: web
    name: xsd-editor-api
    env: node
    region: oregon
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://your-app-name.netlify.app
      - key: MAX_FILE_SIZE
        value: 50MB
